github.com:
    users:
        Narr0wB:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Narr0wB
